version: '3.6'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper 
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: kthare10/kafka:2.11-2.0.1
    build:
      context: ./2.11-2.0.1
      dockerfile: Dockerfile
    container_name: kafka
    restart: always
    depends_on:
        - zookeeper
    ports:
        - 9092:9092
    environment:
        ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT://LOCALIP:9092 
